export const HUMAN_MASCULINE_FIRST = [
    "Ronald",
    "Russell",
    "Stewart",
    "Han",
    "Dammon",
    "Alexander",
    "Julian",
    "Lann",
    "Finnian",
    "Kellan",
    "Ragnar",
    "Eddie",
    "Garrick",
    "Aldric",
    "Marcus",
    "Maxwell",
    "Wesley",
    "Samuel",
    "Tristan",
    "Gabriel",
    "Declan",
    "Donovan",
    "Quentin",
    "Harrison",
    "Nathaniel",
    "Elliott",
    "Xavier",
    "Miles",
    "Lucas",
    "Tobias",
    "Gideon",
    "Arnold",
    "Kaspar",
    "Zane",
    "Brayton",
    "Gordon",
    "Walton",
    "Damian",
    "Cedric",
    "Jonathan",
    "Test",
    "Test",
    "Thom",
    "Eduard",
    "Stefan",
    "Dorian",
    "Clemens",
    "Ed",
    "Owen"
]

export const HUMAN_FEMININE_FIRST = [
    "Selene",
    "Lyra",
    "Ariana",
    "Britta",
    "Seraphina",
    "Camelia",
    "Isadora",
    "Adelaide",
    "Cecilia",
    "Arabella",
    "Lillian",
    "Rosalind",
    "Genevieve",
    "Marigold",
    "Felicity",
    "Cassandra",
    "Veronica",
    "Matilda",
    "Beatrice",
    "Josephine",
    "Helena",
    "Sandy",
    "Gloriana",
    "Corinna",
    "Katrina",
    "Carina",
    "Alice/Alise",
    "Josslyn",
    "Eleanor",
    "Miranda"
];

export const HUMAN_NEUTRAL_FIRST = [
    "Ash",
    "Billie",
    "Quinn",
    "Blair",
    "Sydney",
    "Payton",
    "Finley",
    "Casey",
    "Reese",
    "Jamie",
    "Morgan",
    "Skylar",
    "Gale"
];

export const HUMAN_FAMILY = [
    "Shaumann",
    "Butters",
    "Buttons",
    "Striker",
    "Windrider",
    "Ashbourne",
    "Ironwood",
    "Oakheart",
    "Frostbane",
    "Firebrand",
    "Whitewood",
    "Swiftarrow",
    "Hawksworth",
    "Riversong",
    "Lightfoot",
    "Nightshade",
    "Shadowcrest",
    "Sunfire",
    "Moonshadow",
    "Leste",
    "Goldback",
    "Wilderwood",
    "Stormbreaker",
    "Writingham",
    "Harrick",
    "Gordon",
    "Hardwin",
    "Barnes",
    "Robin",
    "Clearwater",
    "Von Sydow",
    "Locket",
    "Strongbark",
    "Benson",
    "Blackwell",
    "Fairchild"
];


// ELF
export const ELF_MASCULINE_FIRST = [
    "Meric",
    "Ryker",
    "Elowen",
    "Haldur",
    "Kalias",
    "Rezik",
    "Aloth",
    "Aradin",
    "Thalorin",
    "Caladorn",
    "Elandil",
    "Finrod",
    "Thalion",
    "Valarian",
    "Galadrian",
    "Elorian",
    "Arandur",
    "Lirael",
    "Maol",
    "Tahan",
    "Quill"
];

export const ELF_FEMININE_FIRST = [
    "Aleida",
    "Alois",
    "Sina",
    "Nadine",
    "Lynn",
    "Fara",
    "Kana",
    "Gracie",
    "Isolde",
    "Magilla",
    "Atusa",
    "Radeka",
    "Arueshelae",
    "Elara",
    "Nuala",
    "Bahara",
    "Zuri",
    "Eowyn",
    "Isolde",
    "Silfy",
    "Alfira",
    "Corde (Core-day)",
    "Aeris",
    "Caladwen",
    "Finella",
    "Galadriel",
    "Illyria",
    "Lyria",
    "Meliantha",
    "Nariel",
    "Oriel",
    "Rhiannon",
    "Seraphina",
    "Thalindra",
    "Vaelora",
    "Elowyn",
    "Alara",
    "Eloweth",
    "Faeriel",
    "Liriel",
    "Nimue",
    "Ysara",
    "Delemere",
    "Fira"
];

export const ELF_NEUTRAL_FIRST = [
    "Arlen",
    "Belar",
    "Caelum",
    "Darian",
    "Elaris",
    "Finley",
    "Galan",
    "Illyrian",
    "Joren",
    "Kelar",
    "Lior",
    "Meridian",
    "Nyx",
    "Orion",
    "Quinlan",
    "Riven",
    "Selene",
    "Tavian",
    "Vesper"];

export const ELF_FAMILY = [
    "Sevek",
    "Yarrow",
    "Kniles",
    "Galarina",
    "Dholo",
    "Silverleaf",
    "Starfall",
    "Sunfire",
    "Whitewing",
    "Nightshade",
    "Frostwind",
    "Stormblade",
    "Brightwater",
    "Swiftarrow",
    "Oakheart",
    "Faerelorn",
    "Thalorian",
    "Wilderwood",
    "Lightfoot",
    "Dawnmist",
    "Riversong",
    "Fireheart",
    "Shadowbrook",
    "Starblossom",
    "Moonshadow",
    "Rince"
];


// DWARF
export const DWARF_MASCULINE_FIRST = [
    "Ulric",
    "Thrimal",
    "Lagan",
    "Regill",
    "Grebb",
    "Dugan",
    "Arran (pronounced R N)",
    "Lohar",
    "Staunton",
    "Malrum",
    "Bardrak",
    "Krumgarn",
    "Rugan",
    "Thormar",
    "Grimbold",
    "Brogan",
    "Brolin",
    "Haldor",
    "Kharag",
    "Thorvald",
    "Torben",
    "Grimbald",
    "Darrak",
    "Morgrim",
    "Orin",
    "Fargrim",
    "Keldar",
    "Torval",
    "Draven",
    "Balin",
    "Thrain",
    "Brondar"
];

export const DWARF_FEMININE_FIRST = [
    "Effie",
    "Grisha",
    "Thalia",
    "Hilda",
    "Helga",
    "Greta",
    "Astrid",
    "Ingrid",
    "Freya",
    "Sigrid",
    "Erika",
    "Gunhild",
    "Gerda",
    "Thyra",
    "Solveig",
    "Ragnhild",
    "Sigrun",
    "Runa",
    "Dagmar",
    "Brynhild",
    "Hildegarde",
    "Gudrun",
    "Brunhilde"
];

export const DWARF_NEUTRAL_FIRST = [
    "Torin",
    "Dagny",
    "Eir",
    "Fjord",
    "Haf",
    "Jorn",
    "Kari",
    "Mika",
    "Njord",
    "Olin",
    "Ragni",
    "Sven",
    "Tora",
    "Ulf",
    "Vesa",
    "Ylva",
    "Axel",
    "Dag",
    "Edda",
    "Finn"
];

export const DWARF_FAMILY = [
    "Vhane",
    "Ironbeard",
    "Stonehammer",
    "Goldforge",
    "Steelbeard",
    "Axegrinder",
    "Silvervein",
    "Thunderaxe",
    "Rockshield",
    "Deepdelver",
    "Stronghammer",
    "Fireheart",
    "Battleborn",
    "Mountainforge",
    "Grimstone",
    "Ironfist",
    "Stoutshield",
    "Boulderbane",
    "Trueforge",
    "Steelbrow",
    "Ironclad"
];


// HALFLING
export const HALFLING_MASCULINE_FIRST = [
    "Emerson",
    "Fulton",
    "Greybor",
    "Finnean",
    "Sindri",
    "Alder",
    "Bramble",
    "Corbin",
    "Delvin",
    "Eldon",
    "Farley",
    "Harlan",
    "Jasper",
    "Kelton",
    "Linden",
    "Milo",
    "Norbert",
    "Orson",
    "Pippin",
    "Quincy",
    "Rollo",
    "Silas",
    "Thaddeus",
    "Wilbur",
    "Gideon",
    "Meril"
];

export const HALFLING_FEMININE_FIRST = [
    "Daisy",
    "Elsie",
    "Fern",
    "Greta",
    "Hazel",
    "Ivy",
    "Juniper",
    "Lottie",
    "Maisie",
    "Nellie",
    "Olive",
    "Poppy",
    "Sadie",
    "Tansy",
    "Violet",
    "Zinnia",
    "Dottie"
];

export const HALFLING_NEUTRAL_FIRST = [
    "Bailey",
    "Ember",
    "Frankie",
    "Harper",
    "Indigo",
    "Kit",
    "Nico",
    "Pat",
    "Sage",
    "Oakley"
];

export const HALFLING_FAMILY = [
    "Redstream",
    "Elderberry",
    "Greenfield",
    "Willowbrook",
    "Thistleburrow",
    "Bramblethorn",
    "Meadowbrook",
    "Oakenshade",
    "Sweetsong",
    "Fairweather",
    "Honeywell",
    "Smallfoot",
    "Lightfoot",
    "Merryweather",
    "Quickstep",
    "Shortbread",
    "Underhill",
    "Brightwater",
    "Swiftstride",
    "Fuzzytoe",
    "Whistlewick",
    "Merryvale"
];



// GOBLIN
export const GOBLIN_MASCULINE_FIRST = [
    "Olak",
    "Ollik",
    "Grulak",
    "Snik",
    "Kragnok",
    "Throg",
    "Ruzgur",
    "Klik",
    "Urg",
    "Murg",
    "Zog",
    "Grok",
    "Snag",
    "Brik",
    "Flik",
    "Vrak",
    "Drog",
    "Skrag",
    "Grik",
    "Blug",
    "Thruk",
    "Snarz",
    "Brevek"
];

export const GOBLIN_FEMININE_FIRST = [
    "Wendaug",
    "Grizelda",
    "Snarla",
    "Krizza",
    "Thraga",
    "Rukka",
    "Klikka",
    "Urga",
    "Murga",
    "Zorga",
    "Grola",
    "Snaga",
    "Brika",
    "Flikka",
    "Vrakka",
    "Draga",
    "Skraga",
    "Grika",
    "Blugla",
    "Thruka",
    "Snarza"
];

export const GOBLIN_NEUTRAL_FIRST = [
    "Grin",
    "Snik",
    "Kriv",
    "Thrum",
    "Rix",
    "Klik",
    "Urk",
    "Mox",
    "Zix",
    "Grok",
    "Snag",
    "Brix",
    "Flik",
    "Vex",
    "Drak",
    "Skree",
    "Grix",
    "Blinx",
    "Thrix",
    "Snix"
];

export const GOBLIN_FAMILY = [
    "Snagtooth",
    "Grimblood",
    "Ratsbane",
    "Mudhide",
    "Gloomfang",
    "Dirtclaw",
    "Bonecrusher",
    "Darkblade",
    "Ironhide",
    "Shadowgrip",
    "Fangsnarl",
    "Rustbone",
    "Skullcrusher",
    "Shadowmaw",
    "Grimclaw",
    "Rotfang",
    "Blacktooth",
    "Doomclaw",
    "Nightshade",
    "Deathfang"
];

export const FUN_FACT_LIST = [
    "Gets bored easily and can't keep a secret",
     "Conceited and uses a beautiful walking cane",
     "Soft glamorous face and has 4 piercings on her nose",
     "Long curled auburn hair with golden eyes",
     "Female with short white hair and ghostly white skin",
     "Missing their right ear loves partying",
     "Bald head who frequently squints and has a pet dog named Rexy",
     "Scar on their back very talkative disgusted by human architecture"
 ];